import { Inter } from "next/font/google";
import type { Metadata } from "next";

import "./globals.css";
import { cn } from "../../tailwind.config";
const inter = Inter({ subsets: ["latin"] });

import NavBar from "../components/NavBar";

export const metadata: Metadata = {
  title: "Recipe Book",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body
        className={cn(
          inter.className,
          "relative flex min-h-screen min-w-screen flex-col m-4"
        )}
      >
        <NavBar />
        {children}
      </body>
    </html>
  );
}
